name: Testing API
on: [push, pull_request]
jobs:
	testing-api:
		runs-on: ubuntu-latest
		env: 
			SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
		steps:
			- name: Checkout the repo
				uses: actions/checkout@v2
			- name: Creating and Activating Virtual Environment
				run: |
					pip3 install virtualenv
					virtualenv venv
					source venv/bin/activate
			- name: Installing Dependencies
				run: |
					pip install dvc[az]
					pip install -r requirements_test.txt
			- name: Testing API
				run: |
					export AZURE_APPLICATION_CREDENTIALS=${python_utilities/setter.py}
					dvc pull model/model.pkl -r model-tracker
					pytest tests.py
